language: python
cache: pip
dist: xenial

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: TOXENV=flake8 }
      - { python: "3.6", env: TOXENV=flake8 }
      - { python: "3.6", env: TOXENV=black }
      - { python: "3.6", env: TOXENV=readme }

install: pip install tox-travis
script: tox
